version: 2

sources:
  - name: raw        # alias du dataset
    database: lewagonproject-476109
    schema: gz_raw_data  # indique le dataset BigQuery
    loader: bigquery
    description: >
      Dataset brut contenant les données sources issues de Greenweez :
      sales, products et ship. 
      Chaque table correspond à un extrait de données opérationnelles non transformées
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: >
          Ventes de Greenweez — une ligne par produit trouvé dans chaque commande.
        loaded_at_field: date_date
        freshness:
          warn_after: {count: 90, period: day}
        columns:
          - name: date_date
            description: Date d'achat (jour de la commande)
          - name: orders_id
            description: Identifiant unique de la commande
            tests: [not_null]
          - name: pdt_id
            description: Identifiant du produit vendu
            tests: [not_null]
          - name: revenue
            description: Chiffre d'affaires (montant total pour la ligne de commande)
          - name: quantity
            description: Quantité de produits vendus pour cette ligne

      - name: product
        identifier: raw_gz_product
        description: >
          Table des produits Greenweez, contenant les informations de base sur chaque article.
        columns:
          - name: products_id
            description: Identifiant unique du produit
            tests:
              - unique
              - not_null
              
          - name: purchase_price
            description: Prix d'achat du produit pour Greenweez
          - name: category
            description: Catégorie ou famille du produit

      - name: ship
        identifier: raw_gz_ship
        description: >
          Données d’expédition liées aux commandes Greenweez : coûts logistiques et frais d’expédition.
        columns:
          - name: orders_id
            description: Identifiant unique de la commande
            tests:
              - unique0
              - not_null
          - name: shipping_fee
            description: Frais de livraison facturés au client
          - name: ship_cost
            description: Coût d’expédition supporté par Greenweez
          - name: logcost
            description: Coût logistique additionnel

      - name: adwords           
        identifier: raw_gz_adwords  
        description: Données Google Ads (campagnes).
        loaded_at_field: date_date
        freshness:
          warn_after: {count: 90, period: day}
      - name: bing
        identifier: raw_gz_bing
        description: Données Bing Ads (campagnes).
        loaded_at_field: date_date
        freshness:
          warn_after: {count: 90, period: day}
      - name: criteo
        identifier: raw_gz_criteo
        description: Données Criteo (campagnes).
        loaded_at_field: date_date
        freshness:
          warn_after: {count: 90, period: day}
      - name: facebook
        identifier: raw_gz_facebook
        description: Données Facebook Ads (campagnes).
        loaded_at_field: date_date
        freshness:
          warn_after: {count: 90, period: day}

intermediate: 
      - name: int_campaigns_day
        description: >
          Agrégat journalier des coûts et volumes marketing toutes plateformes
          (AdWords, Bing, Criteo, Facebook). 1 ligne = 1 jour.
        columns:
      - name: date_date
        description: Jour d'agrégation
        tests:
          - not_null
          - unique

      - name: total_ads_cost
        description: Dépenses publicitaires totales (toutes plateformes) du jour
        tests:
          - not_null

      - name: total_impressions
        description: Impressions totales du jour (toutes plateformes)
        tests:
          - not_null

      - name: total_clicks
        description: Clics totaux du jour (toutes plateformes)
        tests:
          - not_null

      - name: adwords_ads_cost
        description: Dépenses publicitaires Google Ads du jour

      - name: bing_ads_cost
        description: Dépenses publicitaires Bing du jour

      - name: criteo_ads_cost
        description: Dépenses publicitaires Criteo du jour

      - name: facebook_ads_cost
        description: Dépenses publicitaires Facebook du jour

      - name: nb_adwords
        description: Nombre de lignes/campagnes comptabilisées pour AdWords (jour)

      - name: nb_bing
        description: Nombre de lignes/campagnes comptabilisées pour Bing (jour)

      - name: nb_criteo
        description: Nombre de lignes/campagnes comptabilisées pour Criteo (jour)

      - name: nb_facebook
        description: Nombre de lignes/campagnes comptabilisées pour Facebook (jour)

models:
  - name: int_sales_margin
    description: >
      Joint les ventes et les produits pour calculer, ligne par ligne,
      le coût d’achat (quantity * purchase_price) et la marge (revenue - purchase_cost).
    columns:
      - name: date_date
        description: Date de la ligne de vente
        tests: [not_null]
      - name: orders_id
        description: Identifiant de commande
        tests: [not_null]
      - name: products_id
        description: Identifiant du produit
        tests:
          - not_null
          - relationships:
              to: ref('stg_raw__product')
              field: products_id
      - name: quantity
        description: Quantité vendue sur la ligne
      - name: revenue
        description: Revenu de la ligne de commande
      - name: purchase_price
        description: Prix d’achat unitaire du produit
      - name: purchase_cost
        description: Coût d’achat total de la ligne (quantity * purchase_price)
      - name: margin
        description: Marge brute de la ligne (revenue - purchase_cost)

  - name: int_orders_margin
    description: >
      Agrège int_sales_margin au niveau commande (1 ligne = 1 order_id) :
      revenue, quantity, purchase_cost et margin par commande.
    columns:
      - name: orders_id
        description: Identifiant unique de la commande (niveau agrégé)
        tests: [not_null, unique]
      - name: date_date
        description: Date associée à la commande
        tests: [not_null]
      - name: revenue
        description: Somme du revenu de la commande
      - name: quantity
        description: Somme des quantités de la commande
      - name: purchase_cost
        description: Coût d’achat total de la commande
      - name: margin
        description: Marge brute totale de la commande

  - name: int_orders_operational
    description: >
      Rejoint les frais d’expédition/logistiques à int_orders_margin et calcule
      la marge opérationnelle : margin + shipping_fee - logcost - ship_cost.
    columns:
      - name: orders_id
        description: Identifiant unique de la commande (niveau agrégé)
        tests: [not_null, unique]
      - name: date_date
        description: Date associée à la commande
        tests: [not_null]
      - name: quantity
        description: Quantité totale dans la commande
      - name: revenue
        description: Revenu total de la commande
      - name: purchase_cost
        description: Coût d’achat total de la commande
      - name: margin
        description: Marge brute de la commande
      - name: shipping_fee
        description: Frais facturés au client pour la livraison
      - name: logcost
        description: Coût logistique de la commande
      - name: ship_cost
        description: Coût d’expédition pour l’entreprise
      - name: operational_margin
        description: Marge opérationnelle (margin + shipping_fee - logcost - ship_cost)

  - name: finance_days
    description: >
      Mart quotidien pour la Finance : transactions, revenu, panier moyen,
      marge opérationnelle, coûts et quantités.
    columns:
      - name: date_date
        description: Jour d’agrégation (1 ligne par jour)
        tests: [not_null, unique]
      - name: total_transactions
        description: Nombre de commandes distinctes du jour
      - name: total_revenue
        description: Somme des revenus du jour
      - name: average_basket
        description: Panier moyen (total_revenue / total_transactions)
      - name: operational_margin
        description: Somme des marges opérationnelles du jour
      - name: total_purchase_cost
        description: Somme des coûts d’achat du jour
      - name: total_shipping_fees
        description: Somme des frais de livraison facturés
      - name: total_log_costs
        description: Somme des coûts logistiques
      - name: total_quantity
        description: Quantité totale vendue
  - name: finance_campaigns_day
    description: >
      Vue mart quotidienne combinant métriques finance (finance_days) et
      agrégats marketing (int_campaigns_day), incluant la marge après
      dépenses publicitaires.
    columns:
      - name: date_date
        description: Jour d'agrégation (clé)
        tests:
          - not_null
          - unique
          - relationships:
              to: ref('finance_days')
              field: date_date

      - name: ads_margin
        description: Marge opérationnelle diminuée des dépenses publicitaires du jour
        tests:
          - not_null

      - name: average_basket
        description: Panier moyen (hérité de finance_days)
        tests:
          - not_null

      - name: operational_margin
        description: Marge opérationnelle du jour (héritée de finance_days)
        tests:
          - not_null

      - name: ads_cost
        description: Dépenses publicitaires totales du jour (toutes plateformes)
        tests:
          - not_null

      - name: ads_impressions
        description: Impressions publicitaires totales du jour
        tests:
          - not_null

      - name: ads_clicks
        description: Clics publicitaires totaux du jour
        tests:
          - not_null

      - name: quantity
        description: Quantité totale vendue (héritée de finance_days)
        tests:
          - not_null

      - name: revenue
        description: Revenu total du jour (hérité de finance_days)
        tests:
          - not_null

      - name: purchase_cost
        description: Coût d’achat total du jour (hérité de finance_days)
        tests:
          - not_null

      - name: margin
        description: Marge brute du jour (héritée de finance_days)
        tests:
          - not_null

      - name: shipping_fee
        description: Frais de livraison facturés (hérité de finance_days)
        tests:
          - not_null

      - name: log_cost
        description: Coûts logistiques (hérité de finance_days)
        tests:
          - not_null

      - name: ship_cost
        description: Coûts d’expédition (hérité de finance_days)
        tests:
          - not_null